
# ####
## Displays
#
# line
# bar
# list
# digit
# list-group
# gauge
# list-details
# indicator
# radar
# heat-map
# map
# pie-chart
# label
#
## Formats
# round
# percent
# fixed
# avg
# mean
# max
# min
# count
#
## Layouts
# overlap
# grid
# stack
# books
# left
# centered
# right
# cross +
# column
# row

#
## Controls
# input
# keyboard
# button
# switch
# range
# x,y
# radial
# radio
# select
# video
# audio
# label
# picture
# upload

# App Information for Store
name: testConfig
version: 0
configVersion: 2
description: The thing
images:
  - http://someimage.com
  - http://youtube.com
  - img.png
imagesDir: assets
icon:
  - assets/icon.png
keywords: test, keyword

integrations:
  - nest
  - robovote

crosstalk:
  - event1
  - event2

configuration:
  foo: bar


dataTypes:
  test: 'string'
  face: 'object'
  power: 'float'
  performance: 'float'
  temperature: 'float'
  control: 'float'
  speed: 'float'

sensors:
  - camera
  - control
  - speed
  - temperature
  - power

# screens are comprised of widgets
screens:
  main:
# Row 1
  - - camera
# Row 2
  - - joystick
    - controls
    - battery
# Row 3
  - - temp
    - power
    - speed
  dashboard:
    - powerBig
    - performance
    - heat

  training:
    - faceScanList


widgets:
  noLayout:
    type: test
    display:
      - gauge
      - map
  faceScanList:
    type: face
    layout: books
    display:
      video:
        size: 2
        service: face
      upload :
        control: upload
        font-size: 3em
        label: 'Add your Face'
      detections :
        # Matrix.type('face').send({ detections: { beard: 0.1, smile: 0.55... } })
        display : list
        grouped : true

  powerBig:
    type: power
    layout: overlap
    filter:
      - now
      - recent
      - last-week
    display: line
    displayList:
      # Matrix.type('power').send({mvhLeft: 1123, estimate: 90, usage: 110 })
      -
        label : millawatt hours remaining
        color: red
        filter: round
        type: mvhLeft
      -
        label : minutes remaining estimate
        color: green
        filter: round
        type: estimate

      -
        label: current load
        color: brown
        weight: 2
        filter: round
        type: usage

  performance:
    type: engine
    label: Performance
    display : gauge
    filter: now
    layout: books
    displayList:
      # Matrix.type('engine').send({rpm: 1123, efficieny: 0.23, torque: 110.12 })
      -
        label: rpm
        color: lightgreen
        type: rpm
      -
        label: efficiency %
        color: lightgreen
        format: percentage
        type: efficiency
      -
        label: Torque lbs
        color: lightgreen
        format: fixed(1)
        type: torque


  heat:
    type: temperature
    layout: grid
    filter:
      - recent
      - now
    display:
      rearWheels:
        label: 'Rear Wheel Temp'
        display: bar
      frontWheels:
        label: 'Front Wheel Temp'
        display: bar
      gears:
        label: 'Gear Temp'
        display: bar
      battery:
        label: 'Battery Temp'
        display: bar



  camera:
   type: video,
   # Label on Display
   label: Robot View,
   display: video
   services:
    - vehicle

  joystick:
    # Matrix.type('joystick').send()
    type: joystick
    display: radial
    control: joystick
    # vvv default
    #controlMap:
    #- joystick: joystick

  controls:
    label: Robot Controls
    type: control-event
    layout: cross
    # these events trigger `control-up` in app
    # are written as "^" in button
    controlEventList:
      ^ : up
      v : down
      o : stop
      <- : left
      -> : right
    control: button
    # important to note

  battery:
    label: Power Level
    layout: books
    displayList:
      -
        type: power
        display: bar
        theme: rainbow
        size: 1
      -
        type: power
        display: line
        filter: last-week
        size: 2

  temp:
    type: temperature
    label: Temp FÂ°

    layout: stack
    display:
      -
        display: digit
        size: 6
        filter: round
      -
        display: indicator
        filter: overheat
        options:
          type: light
          # square, round
          shape: square
          color:
            on: red
            off: white

  power:
    #default
    # type: power
    label : On
    layout: stack
    #alternative to display
    displayList:
      -
        label: On
        display: indicator
        #default
        # type: power
        options:
          colors:
            on: darkred
            off: grey
        size: 2
      -
        label: Powered by Matrix of AdMobilize
        align: right
        gap: 1
        size: 1

  speed:
    label: Speed mph
    type: speed
    display: digit

# dateRange - compose Query
# watch - trigger event
filters:
  recent:
    dateRange: 5 minutes
  now:
    dateRange: 1 minute
  last-week:
    dateRange: 1 week
    # all charts use this range unless otherwise specified
    default: true

  # idk if i like this, shouldn't it be in apps
  overheat:
    watch: gt(120)
  startupBeard:
    watch: gt(0.45)

services:
  vehicle:
    engine: detection
    engineParams:
      zones:
      - exitZone:
        - - 24
          - 33
        - - 24
          - 42
        - - 42
          - 100
        - - 100
          - 110
      speedThresh : 45,
      nightMode: dynamic
  face:
    engine: count
    engineParams:
      minDwell : 1
      minHappy : 0.1
